[package]
name = "zed_aiken"
version = "1.0.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/aiken.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
