[package]
name = "zed_aiken"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/aiken.rs"
crate-type = ["cdylib"]

[dependencies]
html_to_markdown = "0.1.0"
zed_extension_api = "0.0.6"
