id = "aiken"
name = "Aiken"
version = "0.0.1"
schema_version = 1
authors = ["Lucas Rosa <x@rvcas.dev>"]
description = "Aiken language support for Zed"
repository = "https://github.com/aiken-lang/zed-aiken"

[grammars.aiken]
repository = "https://github.com/aiken-lang/tree-sitter-aiken"
commit = "aa7ebdda5940c4481389e3e804346e41cabb4266"

[language_servers.aiken]
language = "Aiken"
name = "Aiken LSP"
